classdef DT_preset_manager < handle
    % PresetManager - Educational Presets for Convolution Visualizer
    %
    % This class manages preset signal combinations designed for educational
    % purposes. Each preset demonstrates different aspects of convolution
    % theory and uses various signal types supported by the visualizer.
    %
    % Author: Ahmed Rabei - TEFO, 2025
    %
    % Preset Categories:
    % - Basic convolution examples
    % - Impulse response demonstrations
    % - Step response examples
    % - Signal processing applications

    properties (Constant, Access = private)
        PRESET_DEFINITIONS = struct(...
            'BasicRectangular', struct(...
                'name', 'Basic Rectangular Pulses', ...
                'desc', 'Fundamental convolution: two rectangular pulses', ...
                'x', '[1, 1, 1]', ...
                'h', '[1, 1]', ...
                'n', '-2:8' ...
            ), ...
            'ImpulseResponse', struct(...
                'name', 'System Impulse Response', ...
                'desc', 'Delta input reveals system characteristics', ...
                'x', 'delta[n]', ...
                'h', '[1, 0.8, 0.6, 0.4, 0.2]', ...
                'n', '-1:8' ...
            ), ...
            'StepResponse', struct(...
                'name', 'Unit Step Response', ...
                'desc', 'Step input shows system accumulation behavior', ...
                'x', 'u[n]', ...
                'h', '[1, 0.5, 0.25]', ...
                'n', '-2:10' ...
            ), ...
            'ExponentialSignals', struct(...
                'name', 'Exponential Decay', ...
                'desc', 'Two exponential signals demonstrate convolution properties', ...
                'x', '0.8^n*u[n]', ...
                'h', '0.6^n*u[n]', ...
                'n', '-1:12' ...
            ), ...
            'SinusoidalFiltering', struct(...
                'name', 'Sinusoidal Filtering', ...
                'desc', 'Sine wave filtered by simple system', ...
                'x', 'sin[0.3*n]', ...
                'h', '[1, 0.5, 0.25]', ...
                'n', '-3:15' ...
            ),...
            'GaussianFiltering', struct(...
                'name', 'Gaussian Signal Processing', ...
                'desc', 'Gaussian signal with exponential system', ...
                'x', 'gauss[n]', ...
                'h', '0.7^n*u[n]', ...
                'n', '-2:10' ...
            ), ...
            'DelayedImpulse', struct(...
                'name', 'Delayed Impulse Response', ...
                'desc', 'Delayed delta function tests time-shift properties', ...
                'x', 'delta[n-2]', ...
                'h', '[1, 0.8, 0.6]', ...
                'n', '-1:8' ...
            ), ...
            'ExponentialSystem', struct(...
                'name', 'Exponential System Response', ...
                'desc', 'Exponential input with system response', ...
                'x', '0.9^n*u[n]', ...
                'h', '[1, 0.5, 0.25, 0.125]', ...
                'n', '-1:12' ...
            ), ...
            'WindowedSine', struct(...
                'name', 'Windowed Sine Wave', ...
                'desc', 'Windowed sinusoidal signal with rectangular filter', ...
                'x', 'sin[0.5*n]*u[n-1]*u[5-n]', ...
                'h', '[1, 1, 1, 1]', ...
                'n', '-2:10' ...
            ), ...
            'MixedSignals', struct(...
                'name', 'Mixed Signal Types', ...
                'desc', 'Combination of different signal types', ...
                'x', 'u[n] + 0.5*sin[0.2*n]', ...
                'h', '[1, 0.8, 0.6]', ...
                'n', '-2:15' ...
            )...
        );
    end

    properties (Access = private)
        PresetKeys
        ValidatedPresets struct % Cache for validated presets
        ValidationEnabled logical = false % Disable validation initially
    end

    methods
        function obj = DT_preset_manager()
            % Constructor - initialize preset keys without validation
            obj.PresetKeys = fieldnames(obj.PRESET_DEFINITIONS);
            % Don't validate during initialization to avoid startup errors
        end

        function presets = getAvailablePresets(obj)
            % Get list of all available presets (including Custom)
            presets = {'Custom'};
            for i = 1:numel(obj.PresetKeys)
                preset_name = obj.PRESET_DEFINITIONS.(obj.PresetKeys{i}).name;
                presets{end+1} = preset_name; %#ok<AGROW>
            end
        end

        function [x_str, h_str, n_str, desc] = getPreset(obj, presetName)
            % Retrieve preset configuration by name
            
            % Handle 'Custom' case
            if strcmp(presetName, 'Custom')
                x_str = '';
                h_str = '';
                n_str = '';
                desc = 'Custom signals - Enter your own expressions';
                return;
            end

            % Search for matching preset
            for i = 1:numel(obj.PresetKeys)
                key = obj.PresetKeys{i};
                if strcmp(obj.PRESET_DEFINITIONS.(key).name, presetName)
                    preset = obj.PRESET_DEFINITIONS.(key);
                    x_str = preset.x;
                    h_str = preset.h;
                    n_str = preset.n;
                    desc = preset.desc;
                    return;
                end
            end

            % Preset not found
            error('PresetManager:NotFound', 'Preset "%s" not found.', presetName);
        end

        function desc = getPresetDescription(obj, presetName)
            % Get just the description of a preset
            try
                [~, ~, ~, desc] = obj.getPreset(presetName);
            catch
                desc = 'Unknown preset';
            end
        end

        function isValid = validatePreset(obj, presetName)
            % Validate that a preset can be parsed correctly
            isValid = false;
            try
                [x_str, h_str, n_str, ~] = obj.getPreset(presetName);
                
                % Skip validation for Custom preset
                if strcmp(presetName, 'Custom')
                    isValid = true;
                    return;
                end

                % Try to parse the preset using DT_signal_parser
                parser = DT_signal_parser();
                n_vec = parser.safeParseTimeVector(n_str);

                % Only validate if expressions are not empty
                if ~isempty(x_str)
                    % Suppress warnings during validation
                    warning('off', 'SignalParser:UnusedTokens');
                    parser.parseSignal(x_str, n_vec);
                    warning('on', 'SignalParser:UnusedTokens');
                end

                if ~isempty(h_str)
                    warning('off', 'SignalParser:UnusedTokens');
                    parser.parseSignal(h_str, n_vec);
                    warning('on', 'SignalParser:UnusedTokens');
                end

                isValid = true;

            catch ME
                if obj.ValidationEnabled
                    warning('PresetManager:ValidationFailed', ...
                        'Preset "%s" failed validation: %s', presetName, ME.message);
                end
                isValid = false;
            end
        end

        function validateAllPresets(obj)
            % Validate all presets (can be called manually)
            obj.ValidationEnabled = true;
            fprintf('PresetManager: Validating %d presets...\n', numel(obj.PresetKeys));

            valid_count = 0;
            for i = 1:numel(obj.PresetKeys)
                key = obj.PresetKeys{i};
                preset_name = obj.PRESET_DEFINITIONS.(key).name;

                if obj.validatePreset(preset_name)
                    obj.ValidatedPresets.(key) = true;
                    valid_count = valid_count + 1;
                else
                    obj.ValidatedPresets.(key) = false;
                    warning('PresetManager:InvalidPreset', ...
                        'Preset "%s" failed validation and may not work correctly.', preset_name);
                end
            end

            fprintf('PresetManager: %d/%d presets validated successfully.\n', ...
                valid_count, numel(obj.PresetKeys));
        end

        function count = getPresetCount(obj)
            % Get total number of presets (excluding Custom)
            count = numel(obj.PresetKeys);
        end

        function keys = getPresetKeys(obj)
            % Get internal keys for all presets
            keys = obj.PresetKeys;
        end

        function enableValidation(obj)
            % Enable validation warnings
            obj.ValidationEnabled = true;
        end

        function disableValidation(obj)
            % Disable validation warnings
            obj.ValidationEnabled = false;
        end
    end
end