classdef CT_preset_manager < handle
    % ContinuousPresetManager - Preset Management for Continuous Convolution Visualizer
    %
    % This class manages predefined signal combinations for educational use
    % in the continuous convolution visualizer. It provides a variety of
    % interesting signal pairs that demonstrate different convolution behaviors.
    %
    % Author: Ahmed Rabei - TEFO, 2025
    %
    % Features:
    % - Educational signal combinations
    % - Theory demonstration examples
    % - Easy preset loading and management
    % - Comprehensive signal library usage

    properties (Constant, Access = private)
        PRESET_DEFINITIONS = struct(...
            'RectRect', struct(...
                'name', 'Rect * Rect  ->  Triangle Or Trapezoid', ...
                'x', 'rect(t,2)', 'h', 'rect(t,1)', ...
                't_start', -4, 't_end', 4, 'dt', 0.05 ...
            ), ...
                'GaussianGaussian', struct(...
                'name', 'Gaussian * Gaussian', ...
                'x', 'gauss(t,0.5)', 'h', 'gauss(t,1)', ...
                't_start', -4, 't_end', 4, 'dt', 0.05 ...
            ), ...
                        'TriangularPulse', struct(...
                'name', 'Tri * Tri (Triangular Convolution)', ...
                'x', 'tri(t,2)', 'h', 'tri(t,1)', ...
                't_start', -3, 't_end', 3, 'dt', 0.05 ...
            ), ...
            'RectExp', struct(...
                'name', 'Rect * Exp Decay', ...
                'x', 'rect(t,1)', 'h', 'exp(-t).*u(t)', ...
                't_start', -3, 't_end', 8, 'dt', 0.05 ...
            ), ...
            'SignalWithImpulse', struct(...
                'name', 'Identity System: Signal * Delta', ...
                'x', '2.*(1-abs(t/2)).*rect(t,4)', 'h', 'delta(t)', ...
                't_start', -5, 't_end', 5, 'dt', 0.05 ...
            ),...
            'StepExp', struct(...
                'name', 'Step * Exp Decay', ...
                'x', 'u(t)', 'h', 'exp(-t).*u(t)', ...
                't_start', -2, 't_end', 100, 'dt', 0.05 ...
            ), ...
            'SineRect', struct(...
                'name', 'Sine * Rect', ...
                'x', 'sin(pi*t)', 'h', 'rect(t,2)', ...
                't_start', -4, 't_end', 4, 'dt', 0.05 ...
            ), ...
            'ImpulseResponse', struct(...
                'name', 'Impulse Response: δ(t) * h(t)', ...
                'x', 'delta(t)', 'h', 'exp(-t).*u(t)', ...
                't_start', -1, 't_end', 6, 'dt', 0.05 ...
            ), ...
            'DelayedImpulse', struct(...
                'name', 'Delayed Impulse: δ(t-1) * rect(t,2)', ...
                'x', 'delta(t-1)', 'h', 'rect(t,2)', ...
                't_start', -2, 't_end', 5, 'dt', 0.02 ...
            ), ...
             'SawtoothExp', struct(...
                'name', 'Sawtooth * Exp (Periodic * Aperiodic)', ...
                'x', 'saw(t,2)', 'h', 'exp(-t).*u(t)', ...
                't_start', -2, 't_end', 8, 'dt', 0.02 ...
            ), ...
            'DoubleImpulse', struct(...
                'name', 'Double Impulse: [δ(t) + δ(t-2)] * tri(t,3)', ...
                'x', 'delta(t) + delta(t-2)', 'h', 'tri(t,3)', ...
                't_start', -2, 't_end', 5, 'dt', 0.02 ...
            ), ...
            'StepResponse', struct(...
                'name', 'Step Response: u(t) * h(t)', ...
                'x', 'u(t)', 'h', 'exp(-t).*sin(2*pi*t).*u(t)', ...
                't_start', -1, 't_end', 6, 'dt', 0.02 ...
            ), ...
            'ModulatedSignal', struct(...
                'name', 'Modulated: cos(πt) * rect(t,2)', ...
                'x', 'cos(pi*t)', 'h', 'rect(t,2)', ...
                't_start', -4, 't_end', 4, 'dt', 0.05 ...
            ), ...
            'DecayingOscillator', struct(...
                'name', 'Decaying Oscillator: e^(-t) * cos(2πt)', ...
                'x', 'exp(-t).*cos(2*pi*t).*u(t)', 'h', 'rect(t,1)', ...
                't_start', -1, 't_end', 6, 'dt', 0.02 ...
            ), ...
            'HighFrequency', struct(...
                'name', 'High Freq: sin(10πt) * rect(t,0.5)', ...
                'x', 'sin(10*pi*t)', 'h', 'rect(t,0.5)', ...
                't_start', -2, 't_end', 2, 'dt', 0.02 ...
            ), ...
            'LowPassFilter', struct(...
                'name', 'Low Pass: tri(t,7) * sinc(t)', ...
                'x', 'tri(t,7)', 'h', 'sinc(t)', ...
                't_start', -15, 't_end', 15, 'dt', 0.05 ...
            ), ...
            'WhiteNoise', struct(...
                'name', 'White Noise * Rect', ...
                'x', 'whitenoise(0.5)', 'h', 'rect(t,2)', ...
                't_start', -3, 't_end', 3, 'dt', 0.05 ...
            ), ...
            'PinkNoise', struct(...
                'name', 'Pink Noise * Exp', ...
                'x', 'pinknoise(0.3)', 'h', 'exp(-t).*u(t)', ...
                't_start', -2, 't_end', 6, 'dt', 0.05 ...
            ), ...
            'BrownNoise', struct(...
                'name', 'Brown Noise * Tri', ...
                'x', 'brownnoise(0.2)', 'h', 'tri(t,3)', ...
                't_start', -4, 't_end', 4, 'dt', 0.05 ...
            ) ...
        );
    end
    
    properties (Access = private)
        PresetKeys
    end
    
    methods
        function obj = CT_preset_manager()
            obj.PresetKeys = fieldnames(obj.PRESET_DEFINITIONS);
        end
        
        function presets = getAvailablePresets(obj)
            presets = cell(1, numel(obj.PresetKeys));
            for i=1:numel(obj.PresetKeys), presets{i}=obj.PRESET_DEFINITIONS.(obj.PresetKeys{i}).name; end
        end
        
        function [x_str, h_str, t_start, t_end, dt] = getPreset(obj, presetName)
            for i = 1:numel(obj.PresetKeys)
                key = obj.PresetKeys{i};
                if strcmp(obj.PRESET_DEFINITIONS.(key).name, presetName)
                    preset=obj.PRESET_DEFINITIONS.(key); x_str=preset.x; h_str=preset.h;
                    t_start=preset.t_start; t_end=preset.t_end; dt=preset.dt;
                    return;
                end
            end
            error('CT_preset_manager:PresetNotFound: Preset not found: %s', presetName);
        end
    end
end